### ISSUE TITLE
Plugin Changes can not be found 

### ISSUE THREAD

**Issue by andreash1972** [cosmocode/changes#65] opened 2022-04-11 12:20 UTC
Hi,
in my installation "Hogfather" (installed today 11.4.2022), the Plugin "Changes Plugin" can not be found by the Plugin-Search in the admin panel.

**Comment by McBart** [comment] 2022-09-05 08:21
This is still the case in Igor

**Comment by GlitterHorn** [comment] 2022-10-18 17:47
Same for Greebo :(

**Comment by gsileno** [comment] 2023-02-15 12:59
Yep, still cannot be found. If I try to install it manually, it seems there is a checksum error. May this be the cause?

**Comment by rtzra** [comment] 2023-08-07 14:52
Same for 2023-04-04a "Jack Jackrum"
Manual installation ok via download https://github.com/cosmocode/changes/zipball/master and "Manual installation"

**Comment by splitbrain** [comment] 2023-12-14 09:18
duplicate of #45

**Closed by splitbrain** 2023-12-14 09:18 UTC
